# Generated by Django 4.2.2 on 2023-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Your geographic scope', max_length=255)),
                ('type_of_applicant', models.CharField(help_text='eg. Individual, small business, etc', max_length=255)),
                ('type_of_fund', models.CharField(help_text='eg. Capital, general operating, etc', max_length=255)),
                ('objectives', models.TextField(help_text='Your mission and goals')),
                ('background', models.TextField(help_text='Little about your history')),
            ],
        ),
    ]
