# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    # environment:
    #   # ALLOW_EMPTY_PASSWORD is recommended only for development.
    #   - ALLOW_EMPTY_PASSWORD=yes
    #   - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
    #   - '6379:6379'
    # volumes:
    #   - 'redis_data:/bitnami/redis/data'
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
  
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:grants-recommender
    container_name: django-recommender-container
    command: python pkg/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  celery:
    restart: always
    build:
      context: .
    command: celery --workdir pkg -A config worker --beat --loglevel=INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app

volumes:
  redis_data:
    driver: local
