# Generated by Django 4.2.6 on 2023-11-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20)),
                ("seed", models.CharField(max_length=20)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CFDA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.PositiveBigIntegerField()),
                ("number", models.CharField(max_length=25)),
                ("program_title", models.CharField(max_length=150)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opportunity_title", models.CharField(max_length=255)),
                ("opportunity_number", models.CharField(max_length=15, unique=True)),
                ("expected_award_no", models.IntegerField()),
                ("eligibility_info", models.TextField()),
                ("description", models.TextField()),
                ("summary", models.TextField(null=True)),
                ("url", models.URLField()),
                ("slug", models.SlugField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="funds.agency",
                    ),
                ),
                (
                    "applicant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="funds.applicanttype",
                    ),
                ),
                (
                    "cfdas",
                    models.ManyToManyField(related_name="funds", to="funds.cfda"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundingActivityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbrv", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=150)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundingInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbrv", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=150)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundProfile",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "location",
                    models.CharField(help_text="Your geographic scope", max_length=255),
                ),
                ("objectives", models.TextField(help_text="Your mission and goals")),
                (
                    "estimated_budget",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("background", models.TextField(help_text="Little about your history")),
                (
                    "project_summary",
                    models.TextField(help_text="Describe the problem to be solved"),
                ),
                ("summary", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                (
                    "applicant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funds.applicanttype",
                    ),
                ),
                (
                    "eligibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funds.fundeligibility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpportunityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("abbrv", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Synopsis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opportunity_id", models.CharField(max_length=25)),
                ("agency_code", models.CharField(max_length=25)),
                ("agency_name", models.CharField(max_length=150)),
                ("agency_phone", models.CharField(max_length=20)),
                ("agency_address_desc", models.CharField(max_length=255)),
                ("agency_contact_phone", models.CharField(max_length=20)),
                ("agency_contact_name", models.CharField(max_length=150)),
                ("agency_contact_desc", models.CharField(max_length=255)),
                ("agency_contact_email", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("response_date", models.DateTimeField()),
                ("posting_date", models.DateTimeField()),
                ("archive_date", models.DateTimeField()),
                ("cost_sharing", models.BooleanField()),
                ("award_ceiling", models.CharField(max_length=100)),
                ("award_ceiling_formatted", models.CharField(max_length=100)),
                ("award_floor", models.CharField(max_length=100)),
                ("award_floor_formatted", models.CharField(max_length=100)),
                ("applicant_eligibilty_desc", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
                (
                    "agency_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synopsises",
                        to="funds.agency",
                    ),
                ),
                (
                    "applicant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funds.applicanttype",
                    ),
                ),
                (
                    "funding_activity_categories",
                    models.ManyToManyField(
                        related_name="synopsis", to="funds.fundingactivitycategory"
                    ),
                ),
                (
                    "funding_instruement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funds.fundinginstrument",
                    ),
                ),
                (
                    "top_agency_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="funds.agency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="funds.fund"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funds.fundprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fundprofile",
            name="matches",
            field=models.ManyToManyField(
                related_name="profiles", through="funds.Recommendation", to="funds.fund"
            ),
        ),
        migrations.AddField(
            model_name="fundprofile",
            name="opportunity_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="funds.opportunitycategory",
            ),
        ),
        migrations.AddField(
            model_name="fundprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="eligibility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funds",
                to="funds.fundeligibility",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="opportunity_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funds",
                to="funds.opportunitycategory",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="synopsis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="funds.synopsis"
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="top_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="funds.agency"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("profile", "fund"), name="unique_profile_fund"
            ),
        ),
    ]
