# Generated by Django 4.2.2 on 2023-10-15 21:17

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fundprofile',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fundprofile',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
