# Generated by Django 4.2.6 on 2023-11-16 13:34

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fund_summary_fundprofile_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
